backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: starczi
#     api_key: 648339465694698

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: '{{slug}}/{{slug}}'
    # media_folder: static/images/uploads
    # public_folder: /images/uploads
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
